baseURL = 'https://winston.sirapollokaggwaschools.co.ug/'
locale = 'en-us'
title = 'Winston Day and Boarding Primary School - Kawempe'
theme = "saks-theme"


[params]
logo = "/img/logo.png"
mainSchool = false
