backend:
  name: github
  repo: sakschools/saks-fairways
  branch: main
  site_domain: https://winston.sirapollokaggwaschools.co.ug
  base_url: https://winston.sirapollokaggwaschools.co.ug
  auth_endpoint: /api/auth

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: 'blog'
    label: 'Blog Posts'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: "blog/{{slug}}"
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DDTHH:mm:ssZ' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image',
          choose_url: false,
          media_library: { config: { folder: 'posts' } }
        }
      - { label: 'Content', name: 'body', widget: 'markdown' }
